/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICollectionValidator,
  ICollectionValidatorInterface,
} from "../ICollectionValidator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_collection",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "isValidCollection",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICollectionValidator__factory {
  static readonly abi = _abi;
  static createInterface(): ICollectionValidatorInterface {
    return new utils.Interface(_abi) as ICollectionValidatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICollectionValidator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICollectionValidator;
  }
}
