/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICollectionManager,
  ICollectionManagerInterface,
} from "../ICollectionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_forwarder",
        type: "address",
      },
      {
        internalType: "address",
        name: "_collection",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "manageCollection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICollectionManager__factory {
  static readonly abi = _abi;
  static createInterface(): ICollectionManagerInterface {
    return new utils.Interface(_abi) as ICollectionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICollectionManager {
    return new Contract(address, _abi, signerOrProvider) as ICollectionManager;
  }
}
