/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRarities, IRaritiesInterface } from "../IRarities";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "rarity",
        type: "string",
      },
    ],
    name: "getRarityByName",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "maxSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
        ],
        internalType: "struct IRarities.Rarity",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRarities__factory {
  static readonly abi = _abi;
  static createInterface(): IRaritiesInterface {
    return new utils.Interface(_abi) as IRaritiesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRarities {
    return new Contract(address, _abi, signerOrProvider) as IRarities;
  }
}
