/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MetaTxForwarder,
  MetaTxForwarderInterface,
} from "../MetaTxForwarder";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "forwardMetaTx",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610244806100206000396000f3fe60806040526004361061001e5760003560e01c806307bd352214610023575b600080fd5b610036610031366004610121565b61004c565b60405161004391906101bb565b60405180910390f35b6060600080856001600160a01b031634868660405161006c9291906101ab565b60006040518083038185875af1925050503d80600081146100a9576040519150601f19603f3d011682016040523d82523d6000602084013e6100ae565b606091505b5091509150816101185760405162461bcd60e51b815260206004820152602b60248201527f4d6574615478466f7277617264657223666f72776172644d65746154783a202060448201526a10d0531317d1905253115160aa1b606482015260840160405180910390fd5b95945050505050565b600080600060408486031215610135578283fd5b83356001600160a01b038116811461014b578384fd5b925060208401356001600160401b0380821115610166578384fd5b818601915086601f830112610179578384fd5b813581811115610187578485fd5b876020828501011115610198578485fd5b6020830194508093505050509250925092565b8183823760009101908152919050565b6000602080835283518082850152825b818110156101e7578581018301518582016040015282016101cb565b818111156101f85783604083870101525b50601f01601f191692909201604001939250505056fea26469706673582212206abae808508f2cd7063e89810065638b4e9a86128acdf4b6f6e254fea342177f64736f6c63430008040033";

export class MetaTxForwarder__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MetaTxForwarder> {
    return super.deploy(overrides || {}) as Promise<MetaTxForwarder>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MetaTxForwarder {
    return super.attach(address) as MetaTxForwarder;
  }
  connect(signer: Signer): MetaTxForwarder__factory {
    return super.connect(signer) as MetaTxForwarder__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MetaTxForwarderInterface {
    return new utils.Interface(_abi) as MetaTxForwarderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MetaTxForwarder {
    return new Contract(address, _abi, signerOrProvider) as MetaTxForwarder;
  }
}
